import { StyleSheet } from "@/lib/pdf";

export const pdfStyles = StyleSheet.create({
  page: {
    padding: 20,
    fontFamily: "Helvetica",
    backgroundColor: "#ffffff",
    color: "#000000",
  },
  // Marco con esquinas redondeadas
  outerFrame: {
    borderWidth: 1.5,
    borderColor: "#000000",
    borderRadius: 12,
    padding: 16,
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  // Portada Header
  headerCenter: {
    alignItems: "center",
    marginBottom: 6,
  },
  instType: {
    fontSize: 9.5,
    fontWeight: "bold",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    textAlign: "center",
  },
  instName: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#1e3a8a",
    marginVertical: 2,
    textAlign: "center",
  },
  instMeta: {
    fontSize: 7,
    color: "#333333",
    textAlign: "center",
    marginTop: 1,
  },
  logoContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 8,
  },
  logoImage: {
    width: 60,
    height: 60,
    objectFit: "contain",
  },
  logoFallback: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: "#1e3a8a",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8fafc",
  },
  logoShieldMotto: {
    fontSize: 7,
    fontStyle: "italic",
    color: "#1e3a8a",
    fontWeight: "bold",
    marginTop: 3,
    textAlign: "center",
  },
  // Títulos Portada
  reportTitle: {
    fontSize: 13.5,
    fontWeight: "bold",
    color: "#b91c1c",
    textAlign: "center",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginTop: 2,
  },
  reportSubtitle: {
    fontSize: 10.5,
    fontWeight: "bold",
    color: "#000000",
    textAlign: "center",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginTop: 2,
    marginBottom: 8,
  },
  // Ficha Estudiante Portada
  studentCard: {
    borderWidth: 1.2,
    borderColor: "#000000",
    borderRadius: 8,
    padding: 9,
    marginVertical: 6,
    backgroundColor: "#ffffff",
  },
  fieldRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  fieldLabel: {
    fontSize: 8.5,
    fontStyle: "italic",
    color: "#111827",
    width: 70,
  },
  fieldValueLine: {
    flex: 1,
    borderBottomWidth: 0.75,
    borderBottomColor: "#000000",
    paddingBottom: 1,
    paddingLeft: 4,
  },
  fieldText: {
    fontSize: 9,
    fontWeight: "bold",
    color: "#000000",
    textTransform: "uppercase",
  },
  // A los padres de familia
  parentsTitle: {
    fontSize: 9,
    fontWeight: "bold",
    textAlign: "center",
    letterSpacing: 0.5,
    marginTop: 6,
    marginBottom: 3,
    textTransform: "uppercase",
  },
  parentsText: {
    fontSize: 7,
    textAlign: "justify",
    lineHeight: 1.3,
    color: "#1f2937",
    marginBottom: 6,
    paddingHorizontal: 4,
  },
  // Tabla Escala Portada
  scaleTable: {
    borderWidth: 1,
    borderColor: "#000000",
    borderRadius: 6,
    width: 210,
    alignSelf: "center",
    overflow: "hidden",
    marginVertical: 4,
  },
  scaleHeader: {
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#000000",
    paddingVertical: 2.5,
    alignItems: "center",
  },
  scaleHeaderText: {
    fontSize: 7,
    fontWeight: "bold",
    textAlign: "center",
  },
  scaleRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#000000",
    minHeight: 12,
  },
  scaleColLetter: {
    width: "45%",
    borderRightWidth: 1,
    borderRightColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 1.5,
  },
  scaleColRange: {
    width: "55%",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 1.5,
  },
  scaleTextBold: {
    fontSize: 7.5,
    fontWeight: "bold",
  },
  scaleText: {
    fontSize: 7,
  },
  // Footer Portada
  footerCenter: {
    alignItems: "center",
    marginTop: 6,
  },
  yearBadge: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 3,
  },
  yearLabel: {
    fontSize: 8.5,
    fontStyle: "italic",
    marginRight: 5,
  },
  yearBox: {
    borderWidth: 1,
    borderColor: "#000000",
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  yearText: {
    fontSize: 9.5,
    fontWeight: "bold",
    letterSpacing: 2,
  },
  mottoText: {
    fontSize: 10,
    fontStyle: "italic",
    color: "#000000",
    marginTop: 2,
    textAlign: "center",
  },

  // ═══════════════════════════════════════════════════════════
  // PÁGINA 2: MATRIZ DE CALIFICACIONES & OBSERVACIONES
  // ═══════════════════════════════════════════════════════════
  page2Frame: {
    borderWidth: 1.5,
    borderColor: "#000000",
    borderRadius: 10,
    padding: 10,
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  mainTable: {
    borderWidth: 1.2,
    borderColor: "#000000",
    borderRadius: 4,
    overflow: "hidden",
  },
  // Header Filas
  tblHeaderRow1: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#000000",
    minHeight: 16,
    backgroundColor: "#ffffff",
    alignItems: "center",
  },
  tblHeaderRow2: {
    flexDirection: "row",
    borderBottomWidth: 1.2,
    borderBottomColor: "#000000",
    minHeight: 13,
    backgroundColor: "#ffffff",
    alignItems: "center",
  },

  // Geometry
  colAsig: {
    width: "36%",
    borderRightWidth: 1,
    borderRightColor: "#000000",
    justifyContent: "center",
  },
  colBimGroup: {
    width: "44%",
    borderRightWidth: 1,
    borderRightColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
  },
  colPromAnual: {
    width: "10%",
    borderRightWidth: 1,
    borderRightColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
  },
  colRecup: { width: "10%", alignItems: "center", justifyContent: "center" },

  colBimSubNum: {
    width: "5.5%",
    borderRightWidth: 0.5,
    borderRightColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
  },
  colBimSubLit: {
    width: "5.5%",
    borderRightWidth: 1,
    borderRightColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
  },

  // Filas de datos
  dataRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#000000",
    minHeight: 12.5,
    alignItems: "center",
  },
  cellAsigText: {
    fontSize: 6.8,
    fontWeight: "bold",
    paddingLeft: 4,
    color: "#000000",
  },
  cellNumText: {
    fontSize: 6.8,
    textAlign: "center",
    color: "#000000",
  },
  cellLitText: {
    fontSize: 6.8,
    fontWeight: "bold",
    textAlign: "center",
    color: "#000000",
  },
  cellSummaryTitle: {
    fontSize: 6.8,
    fontWeight: "bold",
    paddingLeft: 4,
    color: "#000000",
  },
  summaryRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#000000",
    minHeight: 12.5,
    alignItems: "center",
  },
  summaryBimCol: {
    width: "11%",
    borderRightWidth: 1,
    borderRightColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
  },

  // Observaciones
  obsTable: {
    borderWidth: 1,
    borderColor: "#000000",
    borderRadius: 4,
    marginTop: 5,
    overflow: "hidden",
  },
  obsHeaderRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#000000",
    minHeight: 13,
    alignItems: "center",
    backgroundColor: "#ffffff",
  },
  obsRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#000000",
    minHeight: 16,
    alignItems: "center",
  },
  colBimLabel: {
    width: "20%",
    borderRightWidth: 1,
    borderRightColor: "#000000",
    paddingLeft: 4,
    justifyContent: "center",
  },
  colFirmaPadre: {
    width: "32%",
    borderRightWidth: 1,
    borderRightColor: "#000000",
    paddingHorizontal: 3,
    justifyContent: "center",
    alignItems: "center",
  },
  colObsText: {
    width: "48%",
    paddingHorizontal: 4,
    justifyContent: "center",
  },

  // Tabla Criterios MINEDU
  criteriosTable: {
    borderWidth: 1,
    borderColor: "#000000",
    borderRadius: 4,
    marginTop: 5,
    overflow: "hidden",
  },
  critHeaderRow1: {
    flexDirection: "row",
    borderBottomWidth: 0.75,
    borderBottomColor: "#000000",
    minHeight: 11,
    alignItems: "center",
    backgroundColor: "#ffffff",
  },
  critHeaderRow2: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#000000",
    minHeight: 11,
    alignItems: "center",
    backgroundColor: "#ffffff",
  },
  critRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#000000",
    minHeight: 18,
    alignItems: "center",
  },
  critColGrado: {
    width: "16%",
    borderRightWidth: 1,
    borderRightColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
  },
  critColPromLetter: {
    width: "12%",
    borderRightWidth: 0.5,
    borderRightColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
  },
  critColPromLetterEnd: {
    width: "12%",
    borderRightWidth: 1,
    borderRightColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
  },
  critColRecLetter: {
    width: "12%",
    borderRightWidth: 0.5,
    borderRightColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
  },
  critColRecLetterEnd: {
    width: "12%",
    borderRightWidth: 1,
    borderRightColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
  },
  critColRepite: {
    width: "24%",
    paddingHorizontal: 3,
    justifyContent: "center",
  },

  // Firmas Finales
  signaturesContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-end",
    marginTop: 8,
    paddingHorizontal: 20,
  },
  signatureBox: {
    width: 140,
    alignItems: "center",
  },
  signatureLine: {
    width: "100%",
    borderBottomWidth: 1,
    borderBottomColor: "#000000",
    marginBottom: 2,
  },
  signatureLabel: {
    fontSize: 7,
    fontWeight: "bold",
    color: "#000000",
    textTransform: "uppercase",
    textAlign: "center",
  },
  signatureSub: {
    fontSize: 5.5,
    color: "#333333",
    textAlign: "center",
    marginTop: 1,
  },
});
