
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.2.0
 * Query Engine version: 0c8ef2ce45c83248ab3df073180d5eda9e8be7a3
 */
Prisma.prismaVersion = {
  client: "7.2.0",
  engine: "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.CargoScalarFieldEnum = {
  id: 'id',
  codigo: 'codigo',
  nombre: 'nombre',
  descripcion: 'descripcion',
  jerarquia: 'jerarquia',
  activo: 'activo',
  sistemico: 'sistemico',
  institucionId: 'institucionId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EstadoUsuarioScalarFieldEnum = {
  id: 'id',
  codigo: 'codigo',
  nombre: 'nombre',
  descripcion: 'descripcion',
  color: 'color',
  permiteLogin: 'permiteLogin',
  esActivo: 'esActivo',
  sistemico: 'sistemico',
  orden: 'orden',
  institucionId: 'institucionId',
  activo: 'activo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TipoDocumentoScalarFieldEnum = {
  id: 'id',
  codigo: 'codigo',
  nombre: 'nombre',
  descripcion: 'descripcion',
  categoria: 'categoria',
  requiereAprobacion: 'requiereAprobacion',
  plantillaDefault: 'plantillaDefault',
  formatosPermitidos: 'formatosPermitidos',
  vigencia: 'vigencia',
  sistemico: 'sistemico',
  activo: 'activo',
  institucionId: 'institucionId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TipoEvaluacionScalarFieldEnum = {
  id: 'id',
  codigo: 'codigo',
  nombre: 'nombre',
  descripcion: 'descripcion',
  categoria: 'categoria',
  pesoMinimo: 'pesoMinimo',
  pesoMaximo: 'pesoMaximo',
  pesoSugerido: 'pesoSugerido',
  permiteRecuperacion: 'permiteRecuperacion',
  requiereFecha: 'requiereFecha',
  color: 'color',
  sistemico: 'sistemico',
  activo: 'activo',
  institucionId: 'institucionId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.HistorialEstadoUsuarioScalarFieldEnum = {
  id: 'id',
  usuarioId: 'usuarioId',
  estadoAnteriorId: 'estadoAnteriorId',
  estadoNuevoId: 'estadoNuevoId',
  motivo: 'motivo',
  observaciones: 'observaciones',
  cambiadoPorId: 'cambiadoPorId',
  fechaCambio: 'fechaCambio'
};

exports.Prisma.PermisoScalarFieldEnum = {
  id: 'id',
  codigo: 'codigo',
  nombre: 'nombre',
  descripcion: 'descripcion',
  modulo: 'modulo',
  activo: 'activo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RolPermisoScalarFieldEnum = {
  id: 'id',
  rol: 'rol',
  permisoId: 'permisoId',
  createdAt: 'createdAt'
};

exports.Prisma.UsuarioPermisoScalarFieldEnum = {
  id: 'id',
  usuarioId: 'usuarioId',
  permisoId: 'permisoId',
  fechaInicio: 'fechaInicio',
  fechaFin: 'fechaFin',
  activo: 'activo'
};

exports.Prisma.CargoPermisoScalarFieldEnum = {
  id: 'id',
  cargoId: 'cargoId',
  permisoId: 'permisoId',
  createdAt: 'createdAt'
};

exports.Prisma.InstitucionEducativaScalarFieldEnum = {
  id: 'id',
  codigoModular: 'codigoModular',
  nombreInstitucion: 'nombreInstitucion',
  nombreComercial: 'nombreComercial',
  tipoGestion: 'tipoGestion',
  modalidad: 'modalidad',
  ugel: 'ugel',
  dre: 'dre',
  ubigeo: 'ubigeo',
  direccion: 'direccion',
  distrito: 'distrito',
  provincia: 'provincia',
  departamento: 'departamento',
  telefono: 'telefono',
  email: 'email',
  sitioWeb: 'sitioWeb',
  resolucionCreacion: 'resolucionCreacion',
  fechaCreacion: 'fechaCreacion',
  resolucionActual: 'resolucionActual',
  logo: 'logo',
  directorId: 'directorId',
  cicloEscolarActual: 'cicloEscolarActual',
  fechaInicioClases: 'fechaInicioClases',
  fechaFinClases: 'fechaFinClases',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  emailVerified: 'emailVerified',
  image: 'image',
  role: 'role',
  apellidoPaterno: 'apellidoPaterno',
  apellidoMaterno: 'apellidoMaterno',
  dni: 'dni',
  fechaNacimiento: 'fechaNacimiento',
  sexo: 'sexo',
  estadoCivil: 'estadoCivil',
  nacionalidad: 'nacionalidad',
  direccion: 'direccion',
  ubigeo: 'ubigeo',
  distrito: 'distrito',
  provincia: 'provincia',
  departamento: 'departamento',
  telefono: 'telefono',
  telefonoEmergencia: 'telefonoEmergencia',
  codigoEstudiante: 'codigoEstudiante',
  codigoSiagie: 'codigoSiagie',
  codigoModular: 'codigoModular',
  numeroExpediente: 'numeroExpediente',
  tipoSangre: 'tipoSangre',
  alergias: 'alergias',
  condicionesMedicas: 'condicionesMedicas',
  contactoEmergencia: 'contactoEmergencia',
  cargoId: 'cargoId',
  estadoId: 'estadoId',
  area: 'area',
  fechaIngreso: 'fechaIngreso',
  fechaSalida: 'fechaSalida',
  numeroContrato: 'numeroContrato',
  nivelAcademicoId: 'nivelAcademicoId',
  turno: 'turno',
  viveConPadres: 'viveConPadres',
  tipoVivienda: 'tipoVivienda',
  serviciosBasicos: 'serviciosBasicos',
  transporteEscolar: 'transporteEscolar',
  becario: 'becario',
  tipoBeca: 'tipoBeca',
  programaSocial: 'programaSocial',
  especialidad: 'especialidad',
  titulo: 'titulo',
  colegioProfesor: 'colegioProfesor',
  fechaContratacion: 'fechaContratacion',
  tipoContrato: 'tipoContrato',
  escalaMagisterial: 'escalaMagisterial',
  ocupacion: 'ocupacion',
  lugarTrabajo: 'lugarTrabajo',
  ingresoFamiliar: 'ingresoFamiliar',
  gradoInstruccion: 'gradoInstruccion',
  institucionId: 'institucionId',
  mustChangePassword: 'mustChangePassword',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RelacionFamiliarScalarFieldEnum = {
  id: 'id',
  padreTutorId: 'padreTutorId',
  hijoId: 'hijoId',
  parentesco: 'parentesco',
  contactoPrimario: 'contactoPrimario',
  autorizadoRecoger: 'autorizadoRecoger',
  viveCon: 'viveCon',
  orden: 'orden'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
};

exports.Prisma.PasswordResetTokenScalarFieldEnum = {
  id: 'id',
  token: 'token',
  expires: 'expires',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.NivelScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  descripcion: 'descripcion',
  institucionId: 'institucionId',
  activo: 'activo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GradoScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  codigo: 'codigo',
  descripcion: 'descripcion',
  orden: 'orden',
  nivelId: 'nivelId',
  activo: 'activo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NivelAcademicoScalarFieldEnum = {
  id: 'id',
  seccion: 'seccion',
  descripcion: 'descripcion',
  capacidad: 'capacidad',
  capacidadMaxima: 'capacidadMaxima',
  aulaAsignada: 'aulaAsignada',
  nivelId: 'nivelId',
  gradoId: 'gradoId',
  tutorId: 'tutorId',
  institucionId: 'institucionId',
  anioAcademico: 'anioAcademico',
  activo: 'activo',
  turno: 'turno',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PeriodoAcademicoScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  tipo: 'tipo',
  numero: 'numero',
  fechaInicio: 'fechaInicio',
  fechaFin: 'fechaFin',
  anioEscolar: 'anioEscolar',
  activo: 'activo',
  institucionId: 'institucionId'
};

exports.Prisma.AreaCurricularScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  codigo: 'codigo',
  descripcion: 'descripcion',
  orden: 'orden',
  color: 'color',
  activa: 'activa',
  competenciasTexto: 'competenciasTexto',
  institucionId: 'institucionId',
  creditos: 'creditos',
  nivelId: 'nivelId',
  parentId: 'parentId'
};

exports.Prisma.CursoScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  codigo: 'codigo',
  descripcion: 'descripcion',
  anioAcademico: 'anioAcademico',
  horasSemanales: 'horasSemanales',
  creditos: 'creditos',
  areaCurricularId: 'areaCurricularId',
  nivelAcademicoId: 'nivelAcademicoId',
  gradoId: 'gradoId',
  profesorId: 'profesorId',
  activo: 'activo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  alcance: 'alcance',
  institucionId: 'institucionId',
  nivelId: 'nivelId'
};

exports.Prisma.HorarioScalarFieldEnum = {
  id: 'id',
  cursoId: 'cursoId',
  diaSemana: 'diaSemana',
  horaInicio: 'horaInicio',
  horaFin: 'horaFin',
  aula: 'aula'
};

exports.Prisma.MatriculaScalarFieldEnum = {
  id: 'id',
  numeroMatricula: 'numeroMatricula',
  estudianteId: 'estudianteId',
  nivelAcademicoId: 'nivelAcademicoId',
  anioAcademico: 'anioAcademico',
  fechaMatricula: 'fechaMatricula',
  estado: 'estado',
  esPrimeraVez: 'esPrimeraVez',
  esRepitente: 'esRepitente',
  procedencia: 'procedencia',
  observaciones: 'observaciones',
  tipoBeca: 'tipoBeca',
  descuentoBeca: 'descuentoBeca'
};

exports.Prisma.MatriculaCursoScalarFieldEnum = {
  id: 'id',
  matriculaId: 'matriculaId',
  cursoId: 'cursoId',
  fechaInscripcion: 'fechaInscripcion',
  estado: 'estado',
  userId: 'userId'
};

exports.Prisma.EvaluacionScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  descripcion: 'descripcion',
  tipoEvaluacionId: 'tipoEvaluacionId',
  fecha: 'fecha',
  fechaLimite: 'fechaLimite',
  peso: 'peso',
  notaMinima: 'notaMinima',
  escalaCalificacion: 'escalaCalificacion',
  cursoId: 'cursoId',
  periodoId: 'periodoId',
  activa: 'activa',
  recuperable: 'recuperable',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  capacidadId: 'capacidadId'
};

exports.Prisma.NotaScalarFieldEnum = {
  id: 'id',
  valor: 'valor',
  valorLiteral: 'valorLiteral',
  valorDescriptivo: 'valorDescriptivo',
  comentario: 'comentario',
  estudianteId: 'estudianteId',
  cursoId: 'cursoId',
  evaluacionId: 'evaluacionId',
  registradoPor: 'registradoPor',
  fechaRegistro: 'fechaRegistro',
  modificadoPor: 'modificadoPor',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AsistenciaScalarFieldEnum = {
  id: 'id',
  fecha: 'fecha',
  presente: 'presente',
  tardanza: 'tardanza',
  horaLlegada: 'horaLlegada',
  justificada: 'justificada',
  justificacion: 'justificacion',
  estudianteId: 'estudianteId',
  cursoId: 'cursoId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  registradoPorId: 'registradoPorId'
};

exports.Prisma.DocumentoScalarFieldEnum = {
  id: 'id',
  tipoDocumentoId: 'tipoDocumentoId',
  descripcion: 'descripcion',
  verificado: 'verificado',
  archivoUrl: 'archivoUrl',
  codigo: 'codigo',
  codigoVerificacion: 'codigoVerificacion',
  contenido: 'contenido',
  createdAt: 'createdAt',
  datosAdicionales: 'datosAdicionales',
  emisorId: 'emisorId',
  estado: 'estado',
  estudianteId: 'estudianteId',
  fechaEmision: 'fechaEmision',
  fechaExpiracion: 'fechaExpiracion',
  firmado: 'firmado',
  formato: 'formato',
  plantilla: 'plantilla',
  titulo: 'titulo',
  updatedAt: 'updatedAt'
};

exports.Prisma.PagoScalarFieldEnum = {
  id: 'id',
  numeroBoleta: 'numeroBoleta',
  concepto: 'concepto',
  descripcion: 'descripcion',
  monto: 'monto',
  moneda: 'moneda',
  fechaVencimiento: 'fechaVencimiento',
  fechaPago: 'fechaPago',
  fechaRegistro: 'fechaRegistro',
  estado: 'estado',
  metodoPago: 'metodoPago',
  referenciaPago: 'referenciaPago',
  numeroOperacion: 'numeroOperacion',
  entidadBancaria: 'entidadBancaria',
  comprobante: 'comprobante',
  recibo: 'recibo',
  estudianteId: 'estudianteId',
  observaciones: 'observaciones',
  descuento: 'descuento',
  mora: 'mora',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  cronogramaPagoId: 'cronogramaPagoId'
};

exports.Prisma.AnuncioScalarFieldEnum = {
  id: 'id',
  titulo: 'titulo',
  contenido: 'contenido',
  resumen: 'resumen',
  imagen: 'imagen',
  fechaPublicacion: 'fechaPublicacion',
  fechaExpiracion: 'fechaExpiracion',
  activo: 'activo',
  dirigidoA: 'dirigidoA',
  importante: 'importante',
  urgente: 'urgente',
  fijado: 'fijado',
  autorId: 'autorId',
  vistas: 'vistas',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EventoScalarFieldEnum = {
  id: 'id',
  titulo: 'titulo',
  descripcion: 'descripcion',
  imagen: 'imagen',
  fechaInicio: 'fechaInicio',
  fechaFin: 'fechaFin',
  horaInicio: 'horaInicio',
  horaFin: 'horaFin',
  fechaLimiteInscripcion: 'fechaLimiteInscripcion',
  ubicacion: 'ubicacion',
  aula: 'aula',
  direccion: 'direccion',
  modalidad: 'modalidad',
  enlaceVirtual: 'enlaceVirtual',
  tipo: 'tipo',
  categoria: 'categoria',
  publico: 'publico',
  dirigidoA: 'dirigidoA',
  capacidadMaxima: 'capacidadMaxima',
  requiereInscripcion: 'requiereInscripcion',
  organizadorId: 'organizadorId',
  estado: 'estado',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CompetenciaScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  descripcion: 'descripcion',
  areaCurricularId: 'areaCurricularId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CapacidadScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  descripcion: 'descripcion',
  competenciaId: 'competenciaId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProspectoScalarFieldEnum = {
  id: 'id',
  dni: 'dni',
  nombre: 'nombre',
  apellidoPaterno: 'apellidoPaterno',
  apellidoMaterno: 'apellidoMaterno',
  fechaNacimiento: 'fechaNacimiento',
  email: 'email',
  telefono: 'telefono',
  direccion: 'direccion',
  gradoInteresId: 'gradoInteresId',
  anioPostulacion: 'anioPostulacion',
  estado: 'estado',
  institucionId: 'institucionId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AdmisionScalarFieldEnum = {
  id: 'id',
  prospectoId: 'prospectoId',
  fechaEntrevista: 'fechaEntrevista',
  resultadoExamen: 'resultadoExamen',
  observaciones: 'observaciones',
  autorizadoPorId: 'autorizadoPorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FichaPsicopedagogicaScalarFieldEnum = {
  id: 'id',
  estudianteId: 'estudianteId',
  especialistaId: 'especialistaId',
  fecha: 'fecha',
  motivo: 'motivo',
  descripcion: 'descripcion',
  recomendaciones: 'recomendaciones',
  categoriaId: 'categoriaId',
  visibleParaPadres: 'visibleParaPadres',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CategoriaIncidenteScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  descripcion: 'descripcion'
};

exports.Prisma.ConceptoPagoScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  montoSugerido: 'montoSugerido',
  moneda: 'moneda',
  activo: 'activo',
  institucionId: 'institucionId',
  moraDiaria: 'moraDiaria'
};

exports.Prisma.CronogramaPagoScalarFieldEnum = {
  id: 'id',
  estudianteId: 'estudianteId',
  conceptoId: 'conceptoId',
  monto: 'monto',
  montoPagado: 'montoPagado',
  fechaVencimiento: 'fechaVencimiento',
  pagado: 'pagado',
  moraAcumulada: 'moraAcumulada',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VariableSistemaScalarFieldEnum = {
  id: 'id',
  clave: 'clave',
  valor: 'valor',
  tipo: 'tipo',
  descripcion: 'descripcion',
  seccion: 'seccion',
  activo: 'activo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ComprobantePagoScalarFieldEnum = {
  id: 'id',
  cronogramaId: 'cronogramaId',
  padreId: 'padreId',
  archivoUrl: 'archivoUrl',
  monto: 'monto',
  bancoOrigen: 'bancoOrigen',
  numeroOperacion: 'numeroOperacion',
  fechaOperacion: 'fechaOperacion',
  estado: 'estado',
  motivoRechazo: 'motivoRechazo',
  verificadoPorId: 'verificadoPorId',
  verificadoEn: 'verificadoEn',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.Role = exports.$Enums.Role = {
  estudiante: 'estudiante',
  profesor: 'profesor',
  administrativo: 'administrativo',
  padre: 'padre'
};

exports.TipoGestion = exports.$Enums.TipoGestion = {
  PUBLICA: 'PUBLICA',
  PRIVADA: 'PRIVADA',
  PARROQUIAL: 'PARROQUIAL',
  CONVENIO: 'CONVENIO'
};

exports.Modalidad = exports.$Enums.Modalidad = {
  PRESENCIAL: 'PRESENCIAL',
  DISTANCIA: 'DISTANCIA',
  SEMIPRESENCIAL: 'SEMIPRESENCIAL'
};

exports.Turno = exports.$Enums.Turno = {
  MANANA: 'MANANA',
  TARDE: 'TARDE',
  NOCHE: 'NOCHE',
  CONTINUO: 'CONTINUO'
};

exports.TipoPeriodo = exports.$Enums.TipoPeriodo = {
  BIMESTRE: 'BIMESTRE',
  TRIMESTRE: 'TRIMESTRE',
  SEMESTRE: 'SEMESTRE',
  ANUAL: 'ANUAL'
};

exports.AlcanceCurso = exports.$Enums.AlcanceCurso = {
  SECCION_ESPECIFICA: 'SECCION_ESPECIFICA',
  TODO_EL_GRADO: 'TODO_EL_GRADO',
  TODO_EL_NIVEL: 'TODO_EL_NIVEL',
  TODO_LA_INSTITUCION: 'TODO_LA_INSTITUCION'
};

exports.EscalaCalificacion = exports.$Enums.EscalaCalificacion = {
  VIGESIMAL: 'VIGESIMAL',
  LITERAL: 'LITERAL',
  DESCRIPTIVA: 'DESCRIPTIVA'
};

exports.EstadoProspecto = exports.$Enums.EstadoProspecto = {
  INTERESADO: 'INTERESADO',
  EVALUANDO: 'EVALUANDO',
  ADMITIDO: 'ADMITIDO',
  RECHAZADO: 'RECHAZADO',
  MATRICULADO: 'MATRICULADO'
};

exports.EstadoComprobante = exports.$Enums.EstadoComprobante = {
  PENDIENTE: 'PENDIENTE',
  EN_REVISION: 'EN_REVISION',
  APROBADO: 'APROBADO',
  RECHAZADO: 'RECHAZADO'
};

exports.Prisma.ModelName = {
  Cargo: 'Cargo',
  EstadoUsuario: 'EstadoUsuario',
  TipoDocumento: 'TipoDocumento',
  TipoEvaluacion: 'TipoEvaluacion',
  HistorialEstadoUsuario: 'HistorialEstadoUsuario',
  Permiso: 'Permiso',
  RolPermiso: 'RolPermiso',
  UsuarioPermiso: 'UsuarioPermiso',
  CargoPermiso: 'CargoPermiso',
  InstitucionEducativa: 'InstitucionEducativa',
  User: 'User',
  RelacionFamiliar: 'RelacionFamiliar',
  Account: 'Account',
  VerificationToken: 'VerificationToken',
  PasswordResetToken: 'PasswordResetToken',
  Nivel: 'Nivel',
  Grado: 'Grado',
  NivelAcademico: 'NivelAcademico',
  PeriodoAcademico: 'PeriodoAcademico',
  AreaCurricular: 'AreaCurricular',
  Curso: 'Curso',
  Horario: 'Horario',
  Matricula: 'Matricula',
  MatriculaCurso: 'MatriculaCurso',
  Evaluacion: 'Evaluacion',
  Nota: 'Nota',
  Asistencia: 'Asistencia',
  Documento: 'Documento',
  Pago: 'Pago',
  Anuncio: 'Anuncio',
  Evento: 'Evento',
  Competencia: 'Competencia',
  Capacidad: 'Capacidad',
  Prospecto: 'Prospecto',
  Admision: 'Admision',
  FichaPsicopedagogica: 'FichaPsicopedagogica',
  CategoriaIncidente: 'CategoriaIncidente',
  ConceptoPago: 'ConceptoPago',
  CronogramaPago: 'CronogramaPago',
  VariableSistema: 'VariableSistema',
  ComprobantePago: 'ComprobantePago'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
