export const studentsSeed = [
  {
    name: "Juan Carlos",
    apellidoPaterno: "Pérez",
    apellidoMaterno: "García",
    dni: "72839451",
    email: "juan.perez@email.com",
    fechaNacimiento: new Date("2012-03-15"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Av. Los Pinos 123",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST001",
    codigoSiagie: "SIAG001",
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "María García",
    dniApoderado: "41234567",
    telefonoApoderado: "987654321",
    parentescoApoderado: "Madre",
  },
  {
    name: "Lucía Fernanda",
    apellidoPaterno: "Torres",
    apellidoMaterno: "Ramírez",
    dni: "83927461",
    email: "lucia.torres@email.com",
    fechaNacimiento: new Date("2013-07-21"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Jr. San Martín 456",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "LA ESPERANZA",
    ubigeo: "130102",
    codigoEstudiante: "EST002",
    codigoSiagie: "SIAG002",
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Carlos Torres",
    dniApoderado: "42345678",
    telefonoApoderado: "912345678",
    parentescoApoderado: "Padre",
  },
  {
    name: "Diego Alejandro",
    apellidoPaterno: "Vargas",
    apellidoMaterno: "Lozano",
    dni: "91827364",
    email: null,
    fechaNacimiento: new Date("2011-11-05"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Mz. B Lt. 12",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "FLORENCIA DE MORA",
    ubigeo: "130103",
    codigoEstudiante: "EST003",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Ana Lozano",
    dniApoderado: "43456789",
    telefonoApoderado: "998877665",
    parentescoApoderado: "Madre",
  },
  {
    name: "Camila",
    apellidoPaterno: "Rojas",
    apellidoMaterno: "Castillo",
    dni: "74561238",
    email: "camila.rojas@email.com",
    fechaNacimiento: new Date("2014-01-18"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Av. América Norte 789",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "VICTOR LARCO",
    ubigeo: "130104",
    codigoEstudiante: "EST004",
    codigoSiagie: "SIAG004",
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Luis Rojas",
    dniApoderado: "44567891",
    telefonoApoderado: "977665544",
    parentescoApoderado: "Padre",
  },
  {
    name: "Mateo Sebastian",
    apellidoPaterno: "Herrera",
    apellidoMaterno: "Silva",
    dni: "75648392",
    email: "mateo.herrera@email.com",
    fechaNacimiento: new Date("2012-09-09"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Calle Los Cedros 321",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "EL PORVENIR",
    ubigeo: "130105",
    codigoEstudiante: "EST005",
    codigoSiagie: "SIAG005",
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Elena Silva",
    dniApoderado: "45678912",
    telefonoApoderado: "966554433",
    parentescoApoderado: "Madre",
  },
  {
    name: "Valentina Sofia",
    apellidoPaterno: "Mendoza",
    apellidoMaterno: "Castro",
    dni: "76543210",
    email: "valentina.mendoza@email.com",
    fechaNacimiento: new Date("2013-05-12"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Calle Los Rosales 142",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "VICTOR LARCO",
    ubigeo: "130104",
    codigoEstudiante: "EST006",
    codigoSiagie: "SIAG006",
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Ricardo Mendoza",
    dniApoderado: "46789012",
    telefonoApoderado: "955443322",
    parentescoApoderado: "Padre",
  },
  {
    name: "Thiago Andre",
    apellidoPaterno: "Salazar",
    apellidoMaterno: "Villanueva",
    dni: "77889900",
    email: null,
    fechaNacimiento: new Date("2012-11-30"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Urb. El Recreo Lt. 5",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST007",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Patricia Villanueva",
    dniApoderado: "47890123",
    telefonoApoderado: "944332211",
    parentescoApoderado: "Madre",
  },
  {
    name: "Ximena",
    apellidoPaterno: "Guzman",
    apellidoMaterno: "Paredes",
    dni: "78901234",
    email: "ximena.guzman@email.com",
    fechaNacimiento: new Date("2014-02-25"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Av. Larco 1020",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "VICTOR LARCO",
    ubigeo: "130111",
    codigoEstudiante: "EST008",
    codigoSiagie: "SIAG008",
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Jorge Guzman",
    dniApoderado: "48901234",
    telefonoApoderado: "933221100",
    parentescoApoderado: "Padre",
  },
  {
    name: "Joaquin",
    apellidoPaterno: "Soto",
    apellidoMaterno: "Espinoza",
    dni: "79012345",
    email: null,
    fechaNacimiento: new Date("2011-08-14"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Barrio Medico 301",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST009",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Carmen Espinoza",
    dniApoderado: "49012345",
    telefonoApoderado: "922110099",
    parentescoApoderado: "Madre",
  },
  {
    name: "Mia Isabel",
    apellidoPaterno: "Bravo",
    apellidoMaterno: "Flores",
    dni: "80123456",
    email: "mia.bravo@email.com",
    fechaNacimiento: new Date("2013-12-05"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Jr. Ayacucho 650",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST010",
    codigoSiagie: "SIAG010",
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Raul Bravo",
    dniApoderado: "50123456",
    telefonoApoderado: "911009988",
    parentescoApoderado: "Padre",
  },
  {
    name: "Nicolas",
    apellidoPaterno: "Vega",
    apellidoMaterno: "Ortiz",
    dni: "81234567",
    email: "nicolas.vega@email.com",
    fechaNacimiento: new Date("2012-04-19"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Calle Las Gemas 210",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "LA ESPERANZA",
    ubigeo: "130102",
    codigoEstudiante: "EST011",
    codigoSiagie: "SIAG011",
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Sonia Ortiz",
    dniApoderado: "51234567",
    telefonoApoderado: "900998877",
    parentescoApoderado: "Madre",
  },
  {
    name: "Antonella",
    apellidoPaterno: "Navarro",
    apellidoMaterno: "Suarez",
    dni: "82345678",
    email: null,
    fechaNacimiento: new Date("2014-06-08"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Av. Mansiche 1500",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST012",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Luis Navarro",
    dniApoderado: "52345678",
    telefonoApoderado: "999888777",
    parentescoApoderado: "Padre",
  },
  {
    name: "Facundo",
    apellidoPaterno: "Reyes",
    apellidoMaterno: "Delgado",
    dni: "83456789",
    email: "facundo.reyes@email.com",
    fechaNacimiento: new Date("2011-01-22"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Urb. San Isidro Etapa 2",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST013",
    codigoSiagie: "SIAG013",
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Monica Delgado",
    dniApoderado: "53456789",
    telefonoApoderado: "988777666",
    parentescoApoderado: "Madre",
  },
  {
    name: "Isabella",
    apellidoPaterno: "Caceres",
    apellidoMaterno: "Medina",
    dni: "84567890",
    email: "isabella.caceres@email.com",
    fechaNacimiento: new Date("2013-03-30"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Jr. Colon 220",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST014",
    codigoSiagie: "SIAG014",
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Andres Caceres",
    dniApoderado: "54567890",
    telefonoApoderado: "977666555",
    parentescoApoderado: "Padre",
  },
  {
    name: "Alvaro",
    apellidoPaterno: "Quispe",
    apellidoMaterno: "Mamani",
    dni: "85678901",
    email: null,
    fechaNacimiento: new Date("2012-07-15"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Mz. F Lote 8",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "EL PORVENIR",
    ubigeo: "130105",
    codigoEstudiante: "EST015",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Yovana Mamani",
    dniApoderado: "55678901",
    telefonoApoderado: "966555444",
    parentescoApoderado: "Madre",
  },
  {
    name: "Aitana",
    apellidoPaterno: "Morales",
    apellidoMaterno: "Vidal",
    dni: "86789012",
    email: "aitana.morales@email.com",
    fechaNacimiento: new Date("2014-09-02"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Calle Las Palmeras 405",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "HUANCHACO",
    ubigeo: "130106",
    codigoEstudiante: "EST016",
    codigoSiagie: "SIAG016",
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Pedro Morales",
    dniApoderado: "56789012",
    telefonoApoderado: "955444333",
    parentescoApoderado: "Padre",
  },
  {
    name: "Leonardo",
    apellidoPaterno: "Silva",
    apellidoMaterno: "Guerrero",
    dni: "87890123",
    email: null,
    fechaNacimiento: new Date("2011-05-18"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Urb. Primavera Calle 2",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST017",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Rosa Guerrero",
    dniApoderado: "57890123",
    telefonoApoderado: "944333222",
    parentescoApoderado: "Madre",
  },
  {
    name: "Flavia",
    apellidoPaterno: "Peña",
    apellidoMaterno: "Ramos",
    dni: "88901234",
    email: "flavia.penya@email.com",
    fechaNacimiento: new Date("2013-10-10"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Av. Roma 450",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST018",
    codigoSiagie: "SIAG018",
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Julio Peña",
    dniApoderado: "58901234",
    telefonoApoderado: "933222111",
    parentescoApoderado: "Padre",
  },
  {
    name: "Gael",
    apellidoPaterno: "Correa",
    apellidoMaterno: "Talledo",
    dni: "89012345",
    email: null,
    fechaNacimiento: new Date("2012-02-28"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Barrio Chicago San Jose",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST019",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Elena Talledo",
    dniApoderado: "59012345",
    telefonoApoderado: "922111000",
    parentescoApoderado: "Madre",
  },
  {
    name: "Luciana",
    apellidoPaterno: "Mejia",
    apellidoMaterno: "Saavedra",
    dni: "90123456",
    email: "luciana.mejia@email.com",
    fechaNacimiento: new Date("2014-04-14"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Urb. Las Quintanas Calle 4",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST020",
    codigoSiagie: "SIAG020",
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Carlos Mejia",
    dniApoderado: "60123456",
    telefonoApoderado: "911000999",
    parentescoApoderado: "Padre",
  },
  {
    name: "Bruno",
    apellidoPaterno: "Ocaña",
    apellidoMaterno: "Salvatierra",
    dni: "91234567",
    email: "bruno.ocanya@email.com",
    fechaNacimiento: new Date("2011-09-20"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Av. Juan Pablo II 880",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST021",
    codigoSiagie: "SIAG021",
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Gloria Salvatierra",
    dniApoderado: "61234567",
    telefonoApoderado: "900999888",
    parentescoApoderado: "Madre",
  },
  {
    name: "Romina",
    apellidoPaterno: "Arce",
    apellidoMaterno: "Farfan",
    dni: "92345678",
    email: null,
    fechaNacimiento: new Date("2013-08-08"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Calle Los Brillantes 505",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST022",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Fabian Arce",
    dniApoderado: "62345678",
    telefonoApoderado: "999000111",
    parentescoApoderado: "Padre",
  },
  {
    name: "Iker",
    apellidoPaterno: "Chavez",
    apellidoMaterno: "Montenegro",
    dni: "93456789",
    email: "iker.chavez@email.com",
    fechaNacimiento: new Date("2012-12-12"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Calle Las Naranjas 110",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "LA ESPERANZA",
    ubigeo: "130102",
    codigoEstudiante: "EST023",
    codigoSiagie: "SIAG023",
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Silvia Montenegro",
    dniApoderado: "63456789",
    telefonoApoderado: "988111222",
    parentescoApoderado: "Madre",
  },
  {
    name: "Danna",
    apellidoPaterno: "Pascual",
    apellidoMaterno: "Ganoza",
    dni: "94567890",
    email: "danna.pascual@email.com",
    fechaNacimiento: new Date("2014-05-05"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Av. America Sur 1200",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST024",
    codigoSiagie: "SIAG024",
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Marcos Pascual",
    dniApoderado: "64567890",
    telefonoApoderado: "977222333",
    parentescoApoderado: "Padre",
  },
  {
    name: "Santiago",
    apellidoPaterno: "Benites",
    apellidoMaterno: "Riva",
    dni: "95678901",
    email: null,
    fechaNacimiento: new Date("2011-03-25"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Calle Los Geranios 203",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST025",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Claudia Riva",
    dniApoderado: "65678901",
    telefonoApoderado: "966333444",
    parentescoApoderado: "Madre",
  },
  {
    name: "Benjamin",
    apellidoPaterno: "Zavaleta",
    apellidoMaterno: "Ruiz",
    dni: "96789012",
    email: null,
    fechaNacimiento: new Date("2020-05-10"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Jr. Pizarro 320",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST026",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Laura Ruiz",
    dniApoderado: "66789012",
    telefonoApoderado: "955444333",
    parentescoApoderado: "Madre",
  },
  {
    name: "Emma Victoria",
    apellidoPaterno: "Cisneros",
    apellidoMaterno: "Del Solar",
    dni: "97890123",
    email: null,
    fechaNacimiento: new Date("2021-08-15"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Av. Larco 1420",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "VICTOR LARCO",
    ubigeo: "130111",
    codigoEstudiante: "EST027",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Victor Cisneros",
    dniApoderado: "67890123",
    telefonoApoderado: "944333222",
    parentescoApoderado: "Padre",
  },
  {
    name: "Liam Gabriel",
    apellidoPaterno: "Bocanegra",
    apellidoMaterno: "Cruz",
    dni: "98901234",
    email: null,
    fechaNacimiento: new Date("2022-11-20"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Calle Las Orquideas 505",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "LA ESPERANZA",
    ubigeo: "130102",
    codigoEstudiante: "EST028",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Sofia Cruz",
    dniApoderado: "68901234",
    telefonoApoderado: "933222111",
    parentescoApoderado: "Madre",
  },
  {
    name: "Zoey Valentina",
    apellidoPaterno: "Mantilla",
    apellidoMaterno: "Quiroz",
    dni: "99012345",
    email: null,
    fechaNacimiento: new Date("2019-03-25"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Mz. J Lt. 24",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "FLORENCIA DE MORA",
    ubigeo: "130103",
    codigoEstudiante: "EST029",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Ricardo Mantilla",
    dniApoderado: "69012345",
    telefonoApoderado: "922111000",
    parentescoApoderado: "Padre",
  },
  {
    name: "Noah Alessandro",
    apellidoPaterno: "Ibañez",
    apellidoMaterno: "Ramos",
    dni: "60123457",
    email: null,
    fechaNacimiento: new Date("2018-06-30"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Calle San Pedro 110",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "EL PORVENIR",
    ubigeo: "130105",
    codigoEstudiante: "EST030",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Rosa Ramos",
    dniApoderado: "70123457",
    telefonoApoderado: "911000999",
    parentescoApoderado: "Madre",
  },
  {
    name: "Mia Isabella",
    apellidoPaterno: "Galarreta",
    apellidoMaterno: "Leyva",
    dni: "61234568",
    email: null,
    fechaNacimiento: new Date("2023-01-05"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Jr. Gamarra 450",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST031",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Jorge Galarreta",
    dniApoderado: "71234568",
    telefonoApoderado: "900999888",
    parentescoApoderado: "Padre",
  },
  {
    name: "Oliver",
    apellidoPaterno: "Carranza",
    apellidoMaterno: "Vasquez",
    dni: "62345679",
    email: null,
    fechaNacimiento: new Date("2017-09-12"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Urb. Primavera Calle A",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST032",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Elena Vasquez",
    dniApoderado: "72345679",
    telefonoApoderado: "999888777",
    parentescoApoderado: "Madre",
  },
  {
    name: "Sofia Antonella",
    apellidoPaterno: "Aranda",
    apellidoMaterno: "Paredes",
    dni: "63456780",
    email: null,
    fechaNacimiento: new Date("2016-12-18"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Calle Los Pinos 200",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "VICTOR LARCO",
    ubigeo: "130111",
    codigoEstudiante: "EST033",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Andres Aranda",
    dniApoderado: "73456780",
    telefonoApoderado: "988777666",
    parentescoApoderado: "Padre",
  },
  {
    name: "Ethan",
    apellidoPaterno: "Miranda",
    apellidoMaterno: "Tirado",
    dni: "64567891",
    email: null,
    fechaNacimiento: new Date("2020-02-28"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Mz. K Lt. 15",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "LA ESPERANZA",
    ubigeo: "130102",
    codigoEstudiante: "EST034",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Clara Tirado",
    dniApoderado: "74567891",
    telefonoApoderado: "977666555",
    parentescoApoderado: "Madre",
  },
  {
    name: "Daniela",
    apellidoPaterno: "Palacios",
    apellidoMaterno: "Mori",
    dni: "65678902",
    email: null,
    fechaNacimiento: new Date("2021-04-14"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Barrio Chicago Lote 5",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST035",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Fernando Palacios",
    dniApoderado: "75678902",
    telefonoApoderado: "966555444",
    parentescoApoderado: "Padre",
  },
  {
    name: "Gael",
    apellidoPaterno: "Moncada",
    apellidoMaterno: "Suarez",
    dni: "66789013",
    email: null,
    fechaNacimiento: new Date("2022-07-07"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Calle Las Gemas 301",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "LA ESPERANZA",
    ubigeo: "130102",
    codigoEstudiante: "EST036",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Silvia Suarez",
    dniApoderado: "76789013",
    telefonoApoderado: "955444333",
    parentescoApoderado: "Madre",
  },
  {
    name: "Luciana Victoria",
    apellidoPaterno: "Ochoa",
    apellidoMaterno: "Huaman",
    dni: "67890124",
    email: null,
    fechaNacimiento: new Date("2019-10-30"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Av. America Sur 1500",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST037",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Carlos Ochoa",
    dniApoderado: "77890124",
    telefonoApoderado: "944333222",
    parentescoApoderado: "Padre",
  },
  {
    name: "Thiago",
    apellidoPaterno: "Vilchez",
    apellidoMaterno: "Castillo",
    dni: "68901235",
    email: null,
    fechaNacimiento: new Date("2018-12-12"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Jr. Ayacucho 880",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST038",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Maritza Castillo",
    dniApoderado: "78901235",
    telefonoApoderado: "933222111",
    parentescoApoderado: "Madre",
  },
  {
    name: "Elena",
    apellidoPaterno: "Sifuentes",
    apellidoMaterno: "Vega",
    dni: "69012346",
    email: null,
    fechaNacimiento: new Date("2023-05-05"),
    sexo: "Femenino",
    nacionalidad: "PERUANA",
    direccion: "Urb. San Isidro Calle 8",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST039",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Jorge Sifuentes",
    dniApoderado: "79012346",
    telefonoApoderado: "922111000",
    parentescoApoderado: "Padre",
  },
  {
    name: "Sebastian",
    apellidoPaterno: "Bernal",
    apellidoMaterno: "Gomez",
    dni: "70123458",
    email: null,
    fechaNacimiento: new Date("2017-02-14"),
    sexo: "Masculino",
    nacionalidad: "PERUANA",
    direccion: "Jr. Colon 110",
    departamento: "LA LIBERTAD",
    provincia: "TRUJILLO",
    distrito: "TRUJILLO",
    ubigeo: "130101",
    codigoEstudiante: "EST040",
    codigoSiagie: null,
    estadoId: "1",
    institucionId: "1",
    nombreApoderado: "Rocio Gomez",
    dniApoderado: "80123458",
    telefonoApoderado: "911000999",
    parentescoApoderado: "Madre",
  },
];
